# generated by fastapi-codegen:
#   filename:  s2-over-ip-connection-init.yml
#   timestamp: 2025-11-11T13:12:14+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Literal, Optional
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field, RootModel, constr


class CommunicationDetailsErrorMessage(BaseModel):
    errorMessage: ErrorMessage
    additionalInfo: Optional[str] = None


class InitiateConnectionPostRequest(BaseModel):
    s2ClientNodeId: S2NodeId
    supportedS2MessageVersions: List[str] = Field(
        ...,
        description='List of supported protocols versions by the client. The server will pick one of the supported protocols versions and return it in the connection details. If no common protocol can be found, an error is returned.',
    )
    supportedCommunicationProtocols: List[CommunicationProtocol]


class InitiateConnectionPostResponse(BaseModel):
    selectedCommunicationProtocol: CommunicationProtocol
    selectedS2MessageVersion: str = Field(
        ...,
        description='The protocol version selected by the server from the list of supported protocol versions provided by the client.',
    )
    accessToken: AccessToken


class UnpairPostRequest(BaseModel):
    s2ClientNodeId: Optional[S2NodeId] = None


class CommunicationDetails(BaseModel):
    communicationProtocol: Literal['WebSocket']


class WebSocketCommunicationDetails(CommunicationDetails):
    websocketToken: CommunicationToken
    websocketUrl: str = Field(..., description='The URL of the communication channel endpoint')


class ConfirmAccessTokenPostResponse(RootModel[WebSocketCommunicationDetails]):
    root: WebSocketCommunicationDetails = Field(..., discriminator='communicationProtocol')


class ErrorMessage(Enum):
    Invalid_combination_of_roles = 'Invalid combination of roles'
    Incompatible_S2_message_versions = 'Incompatible S2 message versions'
    Incompatible_HMAC_hashing_algorithms = 'Incompatible HMAC hashing algorithms'
    S2Node_not_found = 'S2Node not found'
    No_S2Node_provided = 'No S2Node provided'
    No_valid_pairingToken_on_PairingServer = 'No valid pairingToken on PairingServer'
    Parsing_error = 'Parsing error'
    Other = 'Other'


class PairingResponseErrorMessage(BaseModel):
    errorMessage: ErrorMessage
    additionalInfo: Optional[str] = None


class PairingS2NodeId(RootModel[constr(pattern=r'^[0-9a-zA-Z]+$')]):
    root: constr(pattern=r'^[0-9a-zA-Z]+$') = Field(
        ...,
        description='A identifier of the S2 node which is unique for the context of the Endpoint. It is used as a short identifier (since the user might have to type it in manually) for the S2Node, which can be used to lookup the actual S2NodeId.',
        examples=['A0'],
    )


class AccessToken(RootModel[str]):
    root: str = Field(
        ...,
        description='One-time access token for secure access to the S2 message communication channel. It must be renewed every time a client wants to access the S2 message communication channel by calling the requestToken endpoint.This token is valid for one time login, with a maximum 5 years, and should have a minimum length of 32 bytes.',
    )


class S2NodeId(RootModel[UUID]):
    root: UUID = Field(..., description='Unique identifier of the S2 node')


class CommunicationProtocol(Enum):
    WebSocket = 'WebSocket'


class CommunicationToken(RootModel[str]):
    root: str = Field(
        ...,
        description='Token that is used to authorize the communication channel (e.g. WebSocket) between the S2 nodes. It is obtained by calling the requestToken endpoint and is valid for a single connection to the S2 message communication channel.This token is valid for maximum 30 seconds, and should have a minimum length of 32 bytes.',
    )


class S2Role(Enum):
    CEM = 'CEM'
    RM = 'RM'


class Deployment(Enum):
    WAN = 'WAN'
    LAN = 'LAN'


class HmacHashingAlgorithm(Enum):
    SHA256 = 'SHA256'


class HmacChallenge(BaseModel):
    hmacChallenge: str = Field(
        ...,
        description='A base64 encoded HMAC challenge that should be signed by the S2 Node using the pairing token secret as key. The signed challenge should be send to the other S2 Node as part of the pairing process.',
    )
    expirationTime: AwareDatetime = Field(
        ..., description='The time until the HMAC challenge is valid.'
    )


class HmacChallengeResponse(RootModel[str]):
    root: str = Field(
        ...,
        description='The base64 encoded signed HMAC challenge that was calculated by the S2 Node.',
    )


class PairingAttemptId(RootModel[str]):
    root: str = Field(
        ...,
        description='An identifier that is generated by the server for each pairing attempt. It is used as authentication of the client and to keep track of the client requests through the several steps of the pairing process. Once the pairing process is finished (with or without success) the identifier can be discarded.',
    )


class RequestConnectionDetailsPostRequest(BaseModel):
    serverHmacChallengeResponse: HmacChallengeResponse


class FinalizePairingPostRequest(BaseModel):
    success: Optional[bool] = None


class ErrorMessage1(Enum):
    No_valid_token_on_PairingClient = 'No valid token on PairingClient'


class Action(Enum):
    sendS2NodeDescription = 'sendS2NodeDescription'
    preparePairing = 'preparePairing'
    cancelPreparePairing = 'cancelPreparePairing'
    requestPairing = 'requestPairing'


class WaitForPairingPostResponseItem(BaseModel):
    s2ClientNodeId: S2NodeId
    action: Action


class WaitForPairingPostResponse(RootModel[List[WaitForPairingPostResponseItem]]):
    root: List[WaitForPairingPostResponseItem] = Field(..., min_length=1)


class ConnectionDetails(BaseModel):
    initiateConnectionUrl: Optional[AnyUrl] = None
    accessToken: Optional[AccessToken] = None


class S2EndpointDescription(BaseModel):
    name: Optional[str] = None
    logoUri: Optional[AnyUrl] = None
    deployment: Optional[Deployment] = None


class S2NodeDescription(BaseModel):
    id: S2NodeId
    brand: str
    logoUri: Optional[AnyUrl] = None
    type: str
    modelName: str
    userDefinedName: Optional[str] = None
    role: S2Role


class PreparePairingPostRequest(BaseModel):
    s2NodeDescription: S2NodeDescription
    s2EndpointDescription: S2EndpointDescription


class RequestPairingPostRequest(BaseModel):
    s2ClientNodeDescription: S2NodeDescription
    s2ClientEndpointDescription: S2EndpointDescription
    pairingS2NodeId: Optional[PairingS2NodeId] = Field(
        None,
        description='This is a server-assigned identifier of the S2Node that this server represents (which can be part of the pairing token that needs to be entered by the end user). When the server represents only one S2Node (which can be the case for LAN deployment) no pairingS2NodeId has to be provided.',
    )
    supportedCommunicationProtocols: List[CommunicationProtocol]
    supportedS2MessageVersions: List[str] = Field(
        ...,
        description='The versions of the S2 JSON message schemas this S2Node implementation currently supports.',
    )
    supportedHmacHashingAlgorithms: List[HmacHashingAlgorithm]
    clientHmacChallenge: HmacChallenge
    forcePairing: Optional[bool] = Field(
        False,
        description="Forces the server to attempt pairing, even though the S2 message versions are not compatible. In this case the S2Nodes won't be able to communicate after pairing, but this could later be solved through a software update on one or both of the S2Nodes.",
    )


class RequestPairingPostResponse(BaseModel):
    pairingAttemptId: PairingAttemptId
    s2ServerNodeDescription: S2NodeDescription
    s2ServerEndpointDescription: S2EndpointDescription
    selectedHmacHashingAlgorithm: HmacHashingAlgorithm
    clientHmacChallengeResponse: HmacChallengeResponse
    serverHmacChallenge: HmacChallenge


class PostConnectionDetailsPostRequest(BaseModel):
    serverHmacChallengeResponse: HmacChallengeResponse
    connectionDetails: ConnectionDetails


class WaitForPairingPostRequestItem(BaseModel):
    s2ClientNodeId: S2NodeId
    s2NodeDescription: Optional[S2NodeDescription] = None
    s2EndpointDescription: Optional[S2EndpointDescription] = None
    errorMessage: Optional[ErrorMessage1] = None


class WaitForPairingPostRequest(RootModel[List[WaitForPairingPostRequestItem]]):
    root: List[WaitForPairingPostRequestItem]

