
[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[project]
name = "s2auth"
version = "0.1.0a0"
authors = [
    {name = "Flexiblepower", email = "info@info.nl"},
    {name = "Dolf Andringa", email = "dolf@wepositive.energy"},
]
description = "S2 Protocol Python Wrapper"
readme = "README.md"
license = { text = "Apache-2.0" }
requires-python = ">=3.10, < 3.14"
dependencies = [
    "pydantic>=2.8.2",
    "pytz",
    "click",
    "typing-extensions",
    "fastapi",
    "dependency-injector (>=4.48.3,<5.0.0)",
    "pydantic-settings (>=2.5,<3.0)",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

[project.urls]
    "Source code" = "https://github.com/flexiblepower/s2-ws-json-python"

[project.scripts]
server = "s2auth.server.run:main"
client = "s2auth.client.main:main"


[project.optional-dependencies]
db = ["asyncpg (>=0.31.0,<0.32.0)", "sqlalchemy[asyncio] (>=2.0.46,<3.0.0)"]
server = ["asyncpg (>=0.31.0,<0.32.0)", "sqlalchemy[asyncio] (>=2.0.46,<3.0.0)", "fastapi (>=0.128.0,<0.129.0)", "uvicorn[standard] (>=0.32.1,<1.0.0)"]
client = ["sqlalchemy[asyncio] (>=2.0.46,<3.0.0)", "sqlalchemy-utils (>=0.42.1,<0.43.0)", "httpx (>=0.28.1,<0.29.0)"]

[dependency-groups]
docs = [
    "sphinx",
    "sphinx-rtd-theme >= 1.2",
    "sphinx-tabs",
    "sphinx_copybutton",
    "sphinx_fontawesome",
    "sphinxcontrib.httpdomain",
]
dev = [
    "pytest (<9)", # because we want to support python 3.9
    "pytest-coverage",
    "pytest-timer",
    "types-pytz",
    "pyright",
    "ruff",
    "pre-commit",
    "pytest-asyncio (<1.3.0)",
    "aiosqlite (>=0.22.1,<0.23.0)",
    "pytest-mock (>=3.15.1,<4.0.0)",
    "datamodel-code-generator (>=0.53.0,<0.54.0)",
]

[tool.poetry.requires-plugins]
poetry-plugin-shell = "*"


[tool.pytest.ini_options]
testpaths = "tests"
markers = [
    "skip_wire: skip wiring dependencies for this test. Useful if you want to make dependencies in the test."
]
addopts = [
	"--cov=s2auth",
	"--cov-report=html:./unit_test_coverage/",
	"-v",
	"tests/unit/",
]
asyncio_mode = "auto"
asyncio_default_test_loop_scope = "session"
asyncio_default_fixture_loop_scope = "session"

[tool.pyright]
stubPath = "./typings/"
reportImportCycles = false
typeCheckingMode = "strict"
exclude = [
    "./typings/*",
    "**/__pycache__",
    "**/.*",
]
venv = ".venv"
venvPath = "."


[tool.coverage.run]
branch = true
source = ["./src"]

[tool.coverage.report]
exclude_also = [
    "if .*TYPE_CHECKING:",
    "@overload",
    "@typing.overload",
    "class .*\\(Protocol\\):",
    "@abc.abstractmethod",
    "@abstractmethod",
]
show_missing = true

[tool.ruff]
extend-exclude = ["typings/*"]
