
openapi: 3.0.3
info:
  title: My API
  version: 1.0.0
components:
  schemas:
    S2NodeId:
      description: Unique identifier of the S2 node
      type: string
      format: uuid
    CommunicationProtocol:
      type: string
      description: The type of communication protocol supported by the S2 node
      enum:
        - "WebSocket"
    AccessToken:
      description: "One-time access token for secure access to the S2 message communication channel. It must be renewed every time a client wants to access the S2 message communication channel by calling the requestToken endpoint.\
                     This token is valid for one time login, with a maximum 5 years, and should have a minimum length of 32 bytes."
      type: string
      format: byte
    CommunicationToken:
      description: "Token that is used to authorize the communication channel (e.g. WebSocket) between the S2 nodes. It is obtained by calling the requestToken endpoint and is valid for a single connection to the S2 message communication channel.\
                     This token is valid for maximum 30 seconds, and should have a minimum length of 32 bytes."
      type: string
      format: byte
    S2EndpointDescription:
      description: Information about the pairing endpoint of a S2 node
      properties:
        name:
          type: string
        logoUrl:
          type: string
          format: uri
        deployment:
          $ref: "#/components/schemas/Deployment"
    S2NodeDescription:
      required:
        - "id"
        - "brand"
        - "type"
        - "modelName"
        - "role"
      type: object
      description: Information about the S2 node
      properties:
        id:
          $ref: "#/components/schemas/S2NodeId"
        brand:
          type: string
        logoUrl:
          type: string
          format: uri
        type:
          type: string
        modelName:
          type: string
        userDefinedName:
          type: string
        role:
          $ref: "#/components/schemas/S2Role"
    S2Role:
      type: string
      enum:
        - "CEM"
        - "RM"
    Deployment:
      type: string
      enum:
        - "WAN"
        - "LAN"
