# generated by datamodel-codegen:
#   filename:  openapi
#   timestamp: 2026-07-22T09:07:23+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from .s2_connect_wan_endpoint_registry import CountryCode, Status


class EndpointGetParametersQuery(BaseModel):
    region: list[CountryCode] | None = None
    status: Status | None = Status.public
    cem: bool | None = None
    rm: bool | None = None
    limit: Annotated[int | None, Field(ge=1)] = None
    offset: Annotated[int | None, Field(ge=0)] = None
