# generated by datamodel-codegen:
#   filename:  s2-connect-pairing.yml
#   timestamp: 2026-03-26T20:28:20+00:00

from __future__ import annotations
from pydantic import Base64Bytes
from enum import Enum
from pydantic import AnyUrl, BaseModel, Field, RootModel
from typing import Annotated
from .s2_connect_common import (
    AccessToken,
    CommunicationProtocol,
    EndpointDescription,
    NodeDescription,
    NodeId,
)


class ErrorMessage(str, Enum):
    InvalidCombinationOfRoles = "InvalidCombinationOfRoles"
    IncompatibleS2MessageVersions = "IncompatibleS2MessageVersions"
    IncompatibleHmacHashingAlgorithms = "IncompatibleHmacHashingAlgorithms"
    IncompatibleCommunicationProtocols = "IncompatibleCommunicationProtocols"
    NodeNotFound = "NodeNotFound"
    NoNodeIdProvided = "NoNodeIdProvided"
    NoValidPairingTokenOnPairingServer = "NoValidPairingTokenOnPairingServer"
    ParsingError = "ParsingError"
    Other = "Other"


class PairingResponseErrorMessage(BaseModel):
    errorMessage: ErrorMessage
    additionalInfo: str | None = None


class NodeIdAlias(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="A identifier of the node which is unique for the context of the Endpoint. It is used as a short identifier (since the user might have to type it in manually) for the node, which can be used to lookup the actual nodeId.",
            examples=["A0"],
            pattern="^[0-9a-zA-Z]+$",
        ),
    ]


class ConnectionDetails(BaseModel):
    initiateConnectionUrl: AnyUrl
    accessToken: AccessToken
    certificateFingerprint: Annotated[
        dict[str, str] | None,
        Field(
            description='A map containing the fingerprints of the CA certificate that is being used by the server for communication. The key of the map is the hashing algorithm used to create the fingerprint, the value is the fingerprint itself. All fingerprints must refer to the same CA certificate. The key "SHA265" must always be provided. The property certificateFingerprint is mandatory when the pairing client will be come the communication server.'
        ),
    ] = None


class HmacHashingAlgorithm(str, Enum):
    SHA256 = "SHA256"


class HmacChallenge(RootModel[Base64Bytes]):
    root: Annotated[
        Base64Bytes,
        Field(
            description="Random generated binary data encoded using Base64, used as the challenge for the HMAC based challenge response process. The challenge should be send to the other node as part of the pairing process. It must have a length of at least 32 bytes."
        ),
    ]


class HmacChallengeResponse(RootModel[Base64Bytes]):
    root: Annotated[
        Base64Bytes,
        Field(
            description="The Base64 encoded response to the challenge that was calculated by the endpoint."
        ),
    ]


class PairingAttemptId(RootModel[Base64Bytes]):
    root: Annotated[
        Base64Bytes,
        Field(
            description="An identifier that is generated by the server for each pairing attempt. It is used as authentication of the client and to keep track of the client requests through the several steps of the pairing process. Once the pairing process is finished (with or without success) the identifier can be discarded."
        ),
    ]


class RequestConnectionDetailsPostRequest(BaseModel):
    serverHmacChallengeResponse: HmacChallengeResponse


class PostConnectionDetailsPostRequest(BaseModel):
    serverHmacChallengeResponse: HmacChallengeResponse
    connectionDetails: ConnectionDetails


class FinalizePairingPostRequest(BaseModel):
    success: bool | None = None


class CancelPreparePairingPostRequest(BaseModel):
    clientNodeId: NodeId
    serverNodeId: NodeId


class ErrorMessage2(str, Enum):
    NoValidTokenOnPairingClient = "NoValidTokenOnPairingClient"


class Action(str, Enum):
    sendNodeDescription = "sendNodeDescription"
    preparePairing = "preparePairing"
    cancelPreparePairing = "cancelPreparePairing"
    requestPairing = "requestPairing"


class WaitForPairingPostResponseItem(BaseModel):
    clientNodeId: NodeId
    action: Action


class WaitForPairingPostResponse(RootModel[list[WaitForPairingPostResponseItem]]):
    root: Annotated[list[WaitForPairingPostResponseItem], Field(min_length=1)]


class RequestPairingPostRequest(BaseModel):
    clientNodeDescription: NodeDescription
    clientEndpointDescription: EndpointDescription
    nodeId: NodeId | None = None
    nodeIdAlias: NodeIdAlias | None = None
    supportedCommunicationProtocols: list[CommunicationProtocol]
    supportedS2MessageVersions: Annotated[
        list[str],
        Field(
            description="The versions of the S2 JSON message schemas this node implementation currently supports."
        ),
    ]
    supportedHmacHashingAlgorithms: list[HmacHashingAlgorithm]
    clientHmacChallenge: HmacChallenge
    forcePairing: Annotated[
        bool | None,
        Field(
            description="Forces the server to attempt pairing, even though the S2 message versions are not compatible. In this case the nodes won't be able to communicate after pairing, but this could later be solved through a software update on one or both of the nodes."
        ),
    ] = False


class RequestPairingPostResponse(BaseModel):
    pairingAttemptId: PairingAttemptId
    serverNodeDescription: NodeDescription
    serverEndpointDescription: EndpointDescription
    selectedHmacHashingAlgorithm: HmacHashingAlgorithm
    clientHmacChallengeResponse: HmacChallengeResponse
    serverHmacChallenge: HmacChallenge


class NodesGetResponse(RootModel[list[NodeDescription]]):
    root: list[NodeDescription]


class PreparePairingPostRequest(BaseModel):
    clientNodeDescription: NodeDescription
    clientEndpointDescription: EndpointDescription
    serverNodeId: NodeId


class WaitForPairingPostRequestItem(BaseModel):
    clientNodeId: NodeId
    clientNodeDescription: NodeDescription | None = None
    clientEndpointDescription: EndpointDescription | None = None
    errorMessage: ErrorMessage2 | None = None


class WaitForPairingPostRequest(RootModel[list[WaitForPairingPostRequestItem]]):
    root: list[WaitForPairingPostRequestItem]
