# generated by datamodel-codegen:
#   filename:  s2-connect-wan-endpoint-registry.yml
#   timestamp: 2026-07-22T08:01:13+00:00

from __future__ import annotations
from uuid import UUID
from typing import Annotated, Any
from pydantic import AnyUrl, BaseModel, Field, RootModel
from enum import Enum


class Id(RootModel[UUID]):
    root: Annotated[
        UUID, Field(description="Unique identifier of the WAN endpoint registration")
    ]


class CountryCode(RootModel[str]):
    root: Annotated[
        str,
        Field(description="An ISO 3166-1 alpha-2 country code", pattern="^[A-Z]{2}$"),
    ]


class Status(str, Enum):
    public = "public"
    testing = "testing"


class EndpointRecord(BaseModel):
    id: Id
    name: Annotated[
        str, Field(description="User facing name of the endpoint.", max_length=50)
    ]
    description: Annotated[
        Any,
        Field(description="User facing description of the endpoint.", max_length=500),
    ]
    icon32: Annotated[
        AnyUrl,
        Field(
            description="URL of the icon of the endpoint in the size of 32 by 32 pixels and in PNG format."
        ),
    ]
    icon128: Annotated[
        AnyUrl,
        Field(
            description="URL of the icon of the endpoint in the size of 128 by 128 pixels and in PNG format."
        ),
    ]
    icon512: Annotated[
        AnyUrl,
        Field(
            description="URL of the icon of the endpoint in the size of 512 by 512 pixels and in PNG format."
        ),
    ]
    pairingUrl: Annotated[
        AnyUrl,
        Field(
            description="URL of the pairing API. Must include the protocol ('https://') and end with a slash ('/'), and may not include the API version (e.g. 'https://hostname.tld/pairing/')."
        ),
    ]
    regions: Annotated[
        list[CountryCode],
        Field(
            description="The ISO 3166-1 alpha-2 country codes in which this S2 WAN Endpoint operates.",
            min_length=1,
        ),
    ]
    status: Status
    cem: Annotated[
        bool, Field(description="Indicates if this endpoint represents CEMs")
    ]
    rm: Annotated[bool, Field(description="indicates if this endpoint represents RMs")]


class EndpointGetResponse(RootModel[list[EndpointRecord]]):
    root: list[EndpointRecord]
