# generated by datamodel-codegen:
#   filename:  s2-connect-common.yml
#   timestamp: 2026-03-26T20:28:20+00:00

from __future__ import annotations
from pydantic import Base64Bytes
from uuid import UUID
from typing import Annotated
from pydantic import AnyUrl, BaseModel, Field, RootModel, field_serializer
from enum import Enum


class NodeId(RootModel[UUID]):
    root: Annotated[UUID, Field(description="Unique identifier of the node")]

    @field_serializer('root')
    def serialize_uuid(self, value: UUID) -> str:
        return str(value)

class CommunicationProtocol(str, Enum):
    WebSocket = "WebSocket"


class AccessToken(RootModel[Base64Bytes]):
    root: Annotated[
        Base64Bytes,
        Field(
            description="One-time access token for secure access to the S2 message communication channel. It must be renewed every time a client wants to access the S2 message communication channel by calling the requestToken endpoint.This token is valid for one time login, with a maximum 5 years, and should have a minimum length of 32 bytes."
        ),
    ]


class CommunicationToken(RootModel[Base64Bytes]):
    root: Annotated[
        Base64Bytes,
        Field(
            description="Token that is used to authorize the communication channel (e.g. WebSocket) between the nodes. It is obtained by calling the requestToken endpoint and is valid for a single connection to the S2 message communication channel.This token is valid for maximum 30 seconds, and should have a minimum length of 32 bytes."
        ),
    ]


class Role(str, Enum):
    CEM = "CEM"
    RM = "RM"


class Deployment(str, Enum):
    WAN = "WAN"
    LAN = "LAN"


class EndpointDescription(BaseModel):
    name: str | None = None
    logoUrl: AnyUrl | None = None
    deployment: Deployment | None = None


class NodeDescription(BaseModel):
    id: NodeId
    brand: str
    logoUrl: AnyUrl | None = None
    type: str
    modelName: str
    userDefinedName: str | None = None
    role: Role
