# generated by datamodel-codegen:
#   filename:  s2-connect-session-init.yml
#   timestamp: 2026-07-22T08:01:13+00:00

from __future__ import annotations
from pydantic import BaseModel, Field, RootModel
from .s2_connect_common import (
    AccessToken,
    CommunicationProtocol,
    CommunicationToken,
    EndpointDescription,
    NodeDescription,
    NodeId,
)
from typing import Annotated, Literal
from enum import Enum


class CommunicationDetails(BaseModel):
    communicationProtocol: Literal[CommunicationProtocol.WebSocket] = CommunicationProtocol.WebSocket


class WebSocketCommunicationDetails(CommunicationDetails):
    websocketToken: CommunicationToken
    websocketUrl: Annotated[
        str, Field(description="The URL of the communication channel endpoint")
    ]


class ErrorMessage(str, Enum):
    IncompatibleS2MessageVersions = "IncompatibleS2MessageVersions"
    IncompatibleCommunicationProtocols = "IncompatibleCommunicationProtocols"
    NoLongerPaired = "NoLongerPaired"
    ParsingError = "ParsingError"
    Other = "Other"


class CommunicationDetailsErrorMessage(BaseModel):
    errorMessage: ErrorMessage
    additionalInfo: str | None = None


class ConfirmAccessTokenPostResponse(RootModel[WebSocketCommunicationDetails]):
    root: Annotated[
        WebSocketCommunicationDetails, Field(discriminator="communicationProtocol")
    ]


class UnpairPostRequest(BaseModel):
    clientNodeId: NodeId
    serverNodeId: NodeId


class InitiateSessionPostRequest(BaseModel):
    clientNodeId: NodeId
    serverNodeId: NodeId
    supportedS2MessageVersions: Annotated[
        list[str],
        Field(
            description="List of supported protocols versions by the client. The server will pick one of the supported protocols versions and return it in the connection details. If no common protocol can be found, an error is returned."
        ),
    ]
    supportedCommunicationProtocols: list[CommunicationProtocol]
    clientNodeDescription: Annotated[
        NodeDescription | None,
        Field(
            description="Optional field to provide (an updated) NodeDescription. When not provided the server will use the stored description."
        ),
    ] = None
    clientEndpointDescription: Annotated[
        EndpointDescription | None,
        Field(
            description="Optional field to provide (an updated) EndpointDescription. When not provided the server will use the stored description."
        ),
    ] = None


class InitiateSessionPostResponse(BaseModel):
    selectedCommunicationProtocol: CommunicationProtocol
    selectedS2MessageVersion: Annotated[
        str,
        Field(
            description="The protocol version selected by the server from the list of supported protocol versions provided by the client."
        ),
    ]
    accessToken: AccessToken
    serverNodeDescription: Annotated[
        NodeDescription | None,
        Field(
            description="Optional field to provide (an updated) NodeDescription. When not provided the client will use the stored description."
        ),
    ] = None
    serverEndpointDescription: Annotated[
        EndpointDescription | None,
        Field(
            description="Optional field to provide (an updated) EndpointDescription. When not provided the client will use the stored description."
        ),
    ] = None
