# generated by datamodel-codegen:
#   filename:  s2-over-ip-connection-init.yml
#   timestamp: 2026-02-10T09:50:56+00:00

from __future__ import annotations
from pydantic import BaseModel, Field, RootModel
from .s2_over_ip_common import (
    AccessToken,
    CommunicationProtocol,
    CommunicationToken,
    S2EndpointDescription,
    S2NodeDescription,
    S2NodeId,
)
from typing import Annotated
from enum import Enum


class CommunicationDetails(BaseModel):
    communicationProtocol: CommunicationProtocol


class WebSocketCommunicationDetails(CommunicationDetails):
    websocketToken: CommunicationToken
    websocketUrl: Annotated[
        str, Field(description="The URL of the communication channel endpoint")
    ]


class ErrorMessage(Enum):
    IncompatibleS2MessageVersions = "IncompatibleS2MessageVersions"
    IncompatibleCommunicationProtocols = "IncompatibleCommunicationProtocols"
    NoLongerPaired = "NoLongerPaired"
    ParsingError = "ParsingError"
    Other = "Other"


class CommunicationDetailsErrorMessage(BaseModel):
    errorMessage: ErrorMessage
    additionalInfo: str | None = None


class ConfirmAccessTokenPostResponse(RootModel[WebSocketCommunicationDetails]):
    root: Annotated[
        WebSocketCommunicationDetails, Field(discriminator="communicationProtocol")
    ]


class UnpairPostRequest(BaseModel):
    clientS2NodeId: S2NodeId | None = None


class InitiateConnectionPostRequest(BaseModel):
    clientS2NodeId: S2NodeId
    serverS2NodeId: S2NodeId
    supportedS2MessageVersions: Annotated[
        list[str],
        Field(
            description="List of supported protocols versions by the client. The server will pick one of the supported protocols versions and return it in the connection details. If no common protocol can be found, an error is returned."
        ),
    ]
    supportedCommunicationProtocols: list[CommunicationProtocol]
    clientS2NodeDescription: Annotated[
        S2NodeDescription | None,
        Field(
            description="Optional field to provide (an updated) S2NodeDescription. When not provided the server will use the stored description."
        ),
    ] = None
    clientS2EndpointDescription: Annotated[
        S2EndpointDescription | None,
        Field(
            description="Optional field to provide (an updated) S2EndpointDescription. When not provided the server will use the stored description."
        ),
    ] = None


class InitiateConnectionPostResponse(BaseModel):
    selectedCommunicationProtocol: CommunicationProtocol
    selectedS2MessageVersion: Annotated[
        str,
        Field(
            description="The protocol version selected by the server from the list of supported protocol versions provided by the client."
        ),
    ]
    accessToken: AccessToken
    serverS2NodeDescription: Annotated[
        S2NodeDescription | None,
        Field(
            description="Optional field to provide (an updated) S2NodeDescription. When not provided the client will use the stored description."
        ),
    ] = None
    serverS2EndpointDescription: Annotated[
        S2EndpointDescription | None,
        Field(
            description="Optional field to provide (an updated) S2EndpointDescription. When not provided the client will use the stored description."
        ),
    ] = None
