# generated by datamodel-codegen:
#   filename:  s2-over-ip-connection-init.yml
#   timestamp: 2026-02-05T14:28:07+00:00

from __future__ import annotations
from pydantic import BaseModel, Field
from .s2_over_ip_common import CommunicationProtocol, CommunicationToken
from typing import Annotated
from enum import Enum


class CommunicationDetails(BaseModel):
    communicationProtocol: CommunicationProtocol


class WebSocketCommunicationDetails(CommunicationDetails):
    websocketToken: CommunicationToken
    websocketUrl: Annotated[
        str, Field(description="The URL of the communication channel endpoint")
    ]


class ErrorMessage(Enum):
    Incompatible_S2_message_versions = "Incompatible S2 message versions"
    Incompatible_communication_protocols = "Incompatible communication protocols"
    No_longer_paired = "No longer paired"
    Parsing_error = "Parsing error"
    Other = "Other"


class CommunicationDetailsErrorMessage(BaseModel):
    errorMessage: ErrorMessage
    additionalInfo: str | None = None
