# generated by datamodel-codegen:
#   filename:  s2-over-ip-common.yml
#   timestamp: 2026-02-05T15:54:53+00:00

from __future__ import annotations
from uuid import UUID
from typing import Annotated
from pydantic import AnyUrl, Base64Str, BaseModel, Field, RootModel
from enum import Enum


class S2NodeId(RootModel[UUID]):
    root: Annotated[UUID, Field(description="Unique identifier of the S2 node")]


class CommunicationProtocol(Enum):
    WebSocket = "WebSocket"


class AccessToken(RootModel[Base64Str]):
    root: Annotated[
        Base64Str,
        Field(
            description="One-time access token for secure access to the S2 message communication channel. It must be renewed every time a client wants to access the S2 message communication channel by calling the requestToken endpoint.This token is valid for one time login, with a maximum 5 years, and should have a minimum length of 32 bytes."
        ),
    ]


class CommunicationToken(RootModel[Base64Str]):
    root: Annotated[
        Base64Str,
        Field(
            description="Token that is used to authorize the communication channel (e.g. WebSocket) between the S2 nodes. It is obtained by calling the requestToken endpoint and is valid for a single connection to the S2 message communication channel.This token is valid for maximum 30 seconds, and should have a minimum length of 32 bytes."
        ),
    ]


class S2Role(Enum):
    CEM = "CEM"
    RM = "RM"


class Deployment(Enum):
    WAN = "WAN"
    LAN = "LAN"


class S2EndpointDescription(BaseModel):
    name: str | None = None
    logoUri: AnyUrl | None = None
    deployment: Deployment | None = None


class S2NodeDescription(BaseModel):
    id: S2NodeId
    brand: str
    logoUri: AnyUrl | None = None
    type: str
    modelName: str
    userDefinedName: str | None = None
    role: S2Role
