# generated by datamodel-codegen:
#   filename:  s2-over-ip-pairing.yml
#   timestamp: 2026-02-10T09:50:56+00:00

from __future__ import annotations
from enum import Enum
from pydantic import AnyUrl, Base64Str, BaseModel, Field, RootModel
from typing import Annotated
from .s2_over_ip_common import (
    AccessToken,
    CommunicationProtocol,
    S2EndpointDescription,
    S2NodeDescription,
    S2NodeId,
)


class ErrorMessage(Enum):
    InvalidCombinationOfRoles = "InvalidCombinationOfRoles"
    IncompatibleS2MessageVersions = "IncompatibleS2MessageVersions"
    IncompatibleHmacHashingAlgorithms = "IncompatibleHmacHashingAlgorithms"
    IncompatibleCommunicationProtocols = "IncompatibleCommunicationProtocols"
    S2NodeNotFound = "S2NodeNotFound"
    NoS2NodeProvided = "NoS2NodeProvided"
    NoValidPairingTokenOnPairingServer = "NoValidPairingTokenOnPairingServer"
    ParsingError = "ParsingError"
    Other = "Other"


class PairingResponseErrorMessage(BaseModel):
    errorMessage: ErrorMessage
    additionalInfo: str | None = None


class PairingS2NodeId(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="A identifier of the S2 node which is unique for the context of the Endpoint. It is used as a short identifier (since the user might have to type it in manually) for the S2Node, which can be used to lookup the actual S2NodeId.",
            examples=["A0"],
            pattern="^[0-9a-zA-Z]+$",
        ),
    ]


class ConnectionDetails(BaseModel):
    initiateConnectionUrl: AnyUrl | None = None
    accessToken: AccessToken | None = None


class HmacHashingAlgorithm(Enum):
    SHA256 = "SHA256"


class HmacChallenge(RootModel[Base64Str]):
    root: Annotated[
        Base64Str,
        Field(
            description="Random generated binary data encoded using Base64, used as the challenge for the HMAC based challenge response process. The challenge should be send to the other S2 Node as part of the pairing process. It must have a length of at least 32 bytes."
        ),
    ]


class HmacChallengeResponse(RootModel[Base64Str]):
    root: Annotated[
        Base64Str,
        Field(
            description="The Base64 encoded response to the challenge that was calculated by the S2 endpoint."
        ),
    ]


class PairingAttemptId(RootModel[Base64Str]):
    root: Annotated[
        Base64Str,
        Field(
            description="An identifier that is generated by the server for each pairing attempt. It is used as authentication of the client and to keep track of the client requests through the several steps of the pairing process. Once the pairing process is finished (with or without success) the identifier can be discarded."
        ),
    ]


class RequestConnectionDetailsPostRequest(BaseModel):
    serverHmacChallengeResponse: HmacChallengeResponse


class PostConnectionDetailsPostRequest(BaseModel):
    serverHmacChallengeResponse: HmacChallengeResponse
    connectionDetails: ConnectionDetails


class FinalizePairingPostRequest(BaseModel):
    success: bool | None = None


class CancelPreparePairingPostRequest(BaseModel):
    clientS2NodeId: S2NodeId
    serverS2PairingNodeId: PairingS2NodeId | None = None


class ErrorMessage2(Enum):
    NoValidTokenOnPairingClient = "NoValidTokenOnPairingClient"


class Action(Enum):
    sendS2NodeDescription = "sendS2NodeDescription"
    preparePairing = "preparePairing"
    cancelPreparePairing = "cancelPreparePairing"
    requestPairing = "requestPairing"


class WaitForPairingPostResponseItem(BaseModel):
    clientS2NodeId: S2NodeId
    action: Action


class WaitForPairingPostResponse(RootModel[list[WaitForPairingPostResponseItem]]):
    root: Annotated[list[WaitForPairingPostResponseItem], Field(min_length=1)]


class RequestPairingPostRequest(BaseModel):
    clientS2NodeDescription: S2NodeDescription
    clientS2EndpointDescription: S2EndpointDescription
    pairingS2NodeId: Annotated[
        PairingS2NodeId | None,
        Field(
            description="This is a server-assigned identifier of the S2Node that this server represents (which can be part of the pairing token that needs to be entered by the end user). When the server represents only one S2Node (which can be the case for LAN deployment) no pairingS2NodeId has to be provided."
        ),
    ] = None
    supportedCommunicationProtocols: list[CommunicationProtocol]
    supportedS2MessageVersions: Annotated[
        list[str],
        Field(
            description="The versions of the S2 JSON message schemas this S2Node implementation currently supports."
        ),
    ]
    supportedHmacHashingAlgorithms: list[HmacHashingAlgorithm]
    clientHmacChallenge: HmacChallenge
    forcePairing: Annotated[
        bool | None,
        Field(
            description="Forces the server to attempt pairing, even though the S2 message versions are not compatible. In this case the S2Nodes won't be able to communicate after pairing, but this could later be solved through a software update on one or both of the S2Nodes."
        ),
    ] = False


class RequestPairingPostResponse(BaseModel):
    pairingAttemptId: PairingAttemptId
    serverS2NodeDescription: S2NodeDescription
    serverS2EndpointDescription: S2EndpointDescription
    selectedHmacHashingAlgorithm: HmacHashingAlgorithm
    clientHmacChallengeResponse: HmacChallengeResponse
    serverHmacChallenge: HmacChallenge


class S2nodesGetResponse(RootModel[list[S2NodeDescription]]):
    root: list[S2NodeDescription]


class PreparePairingPostRequest(BaseModel):
    clientS2NodeDescription: S2NodeDescription
    clientS2EndpointDescription: S2EndpointDescription
    serverS2PairingNodeId: PairingS2NodeId | None = None


class WaitForPairingPostRequestItem(BaseModel):
    clientS2NodeId: S2NodeId
    clientS2NodeDescription: S2NodeDescription | None = None
    clientS2EndpointDescription: S2EndpointDescription | None = None
    errorMessage: ErrorMessage2 | None = None


class WaitForPairingPostRequest(RootModel[list[WaitForPairingPostRequestItem]]):
    root: list[WaitForPairingPostRequestItem]
