# generated by datamodel-codegen:
#   filename:  s2-over-ip-pairing.yml
#   timestamp: 2026-02-05T14:28:07+00:00

from __future__ import annotations
from enum import Enum
from pydantic import AnyUrl, Base64Str, BaseModel, Field, RootModel
from typing import Annotated
from .s2_over_ip_common import AccessToken


class ErrorMessage(Enum):
    Invalid_combination_of_roles = "Invalid combination of roles"
    Incompatible_S2_message_versions = "Incompatible S2 message versions"
    Incompatible_HMAC_hashing_algorithms = "Incompatible HMAC hashing algorithms"
    Incompatible_communication_protocols = "Incompatible communication protocols"
    S2Node_not_found = "S2Node not found"
    No_S2Node_provided = "No S2Node provided"
    No_valid_pairingToken_on_PairingServer = "No valid pairingToken on PairingServer"
    Parsing_error = "Parsing error"
    Other = "Other"


class PairingResponseErrorMessage(BaseModel):
    errorMessage: ErrorMessage
    additionalInfo: str | None = None


class PairingS2NodeId(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="A identifier of the S2 node which is unique for the context of the Endpoint. It is used as a short identifier (since the user might have to type it in manually) for the S2Node, which can be used to lookup the actual S2NodeId.",
            examples=["A0"],
            pattern="^[0-9a-zA-Z]+$",
        ),
    ]


class ConnectionDetails(BaseModel):
    initiateConnectionUrl: AnyUrl | None = None
    accessToken: AccessToken | None = None


class HmacHashingAlgorithm(Enum):
    SHA256 = "SHA256"


class HmacChallenge(RootModel[Base64Str]):
    root: Annotated[
        Base64Str,
        Field(
            description="Random generated binary data encoded using Base64, used as the challenge for the HMAC based challenge response process. The challenge should be send to the other S2 Node as part of the pairing process. It must have a length of at least 32 bytes."
        ),
    ]


class HmacChallengeResponse(RootModel[Base64Str]):
    root: Annotated[
        Base64Str,
        Field(
            description="The Base64 encoded response to the challenge that was calculated by the S2 endpoint."
        ),
    ]


class PairingAttemptId(RootModel[Base64Str]):
    root: Annotated[
        Base64Str,
        Field(
            description="An identifier that is generated by the server for each pairing attempt. It is used as authentication of the client and to keep track of the client requests through the several steps of the pairing process. Once the pairing process is finished (with or without success) the identifier can be discarded."
        ),
    ]
