name: S2auth
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      # You can test your matrix by printing the current Python version
      - run: ci/setup_dev_environment.sh
      - run: ci/install_dependencies.sh
      - run: ci/test_unit.sh
      - run: ci/lint.sh
      - run: ci/typecheck.sh
