# generated by fastapi-codegen:
#   filename:  s2-over-ip-pairing.yml
#   timestamp: 2025-11-10T15:29:12+00:00

from __future__ import annotations

from typing import Optional, Union

from fastapi import FastAPI

from .models import (
    ConnectionDetails,
    FinalizePairingPostRequest,
    PairingResponseErrorMessage,
    PostConnectionDetailsPostRequest,
    PreparePairingPostRequest,
    RequestConnectionDetailsPostRequest,
    RequestPairingPostRequest,
    RequestPairingPostResponse,
    S2NodeId,
    WaitForPairingPostRequest,
    WaitForPairingPostResponse,
)

app = FastAPI(
    version='1.0-beta',
    title='s2-over-ip pairing and connection initiation',
    description='The HTTP API specification of the pairing process for S2 over IP connections, as well as initiating connections. For more information, please find the specification at [S2 documentation](https://docs.s2standard.org).',
    license={
        'name': 'Apache-2.0',
        'url': 'https://raw.githubusercontent.com/flexiblepower/s2-ws-json/refs/heads/main/LICENSE',
    },
    servers=[{'url': '/v1'}],
)


@app.post('/cancelPreparePairing', response_model=None, tags=['LAN-LAN only extensions'])
def cancel_prepare_pairing(body: S2NodeId = None) -> None:
    """
    Cancel a previous call to preparePairing
    """
    pass


@app.post('/finalizePairing', response_model=None, tags=['Pairing process'])
def confirm_pairing(body: FinalizePairingPostRequest = None) -> None:
    """
    Confirm that the pairing was successful or has failed.
    """
    pass


@app.post('/postConnectionDetails', response_model=None, tags=['Pairing process'])
def post_connection_details(body: PostConnectionDetailsPostRequest = None) -> None:
    """
    Send connection information to the server. This only used if the PairingClient is the CommunicationServer.
    """
    pass


@app.post(
    '/preparePairing',
    response_model=None,
    responses={'400': {'model': PairingResponseErrorMessage}},
    tags=['LAN-LAN only extensions'],
)
def prepare_pairing(
    body: PreparePairingPostRequest = None,
) -> Optional[PairingResponseErrorMessage]:
    """
    Inform the server that a S2Node on the client is planning to attempt pairing with a S2Node on the server.
    """
    pass


@app.post('/requestConnectionDetails', response_model=ConnectionDetails, tags=['Pairing process'])
def request_connection_details(
    body: RequestConnectionDetailsPostRequest = None,
) -> ConnectionDetails:
    """
    Request connection information from the server. This is only used if the PairingServer is also the CommunicationServer.
    """
    pass


@app.post(
    '/requestPairing',
    response_model=RequestPairingPostResponse,
    responses={'400': {'model': PairingResponseErrorMessage}},
    tags=['Pairing process'],
)
def request_pairing(
    body: RequestPairingPostRequest = None,
) -> Union[RequestPairingPostResponse, PairingResponseErrorMessage]:
    """
    Initiate the pairing process.
    """
    pass


@app.post(
    '/waitForPairing', response_model=WaitForPairingPostResponse, tags=['LAN-LAN only extensions']
)
def wait_for_pairing(body: WaitForPairingPostRequest = None) -> WaitForPairingPostResponse:
    """
    Long polling operation to indicate to the server that the client is available for pairing.
    """
    pass
